name: AKS-Deployment
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10.14
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install Dependencies for the app
        run: |
          cd app
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
            login-server: cprimecontainerregistry.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            cd app
            docker build . -t cprimecontainerregistry.azurecr.io/cprimeflask:${{ github.sha }}
            docker push cprimecontainerregistry.azurecr.io/cprimeflask:${{ github.sha }}