name: AKS-Deployment
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10.14
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.14
      - name: Install Dependencies for the app
        run: |
          cd app
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/checkout@master

      - uses: Azure/docker-login@v1
        with:
            login-server: cprimecontainerregistry.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
      - run: |
            cd app
            docker build . -t cprimecontainerregistry.azurecr.io/cprimeflask:${{ github.sha }}
            docker push cprimecontainerregistry.azurecr.io/cprimeflask:${{ github.sha }}
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: cprime-cluster
          resource-group: cprime-rg
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: cprimecontainerregistry.azurecr.io
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          images: |
            cprimecontainerregistry.azurecr.io/k8sflask:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret