name: Flask Application
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12
      - name: Install Dependencies for the app
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt