name: Flask Application
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12
      - name: Install Dependencies for the app
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt